import type {
  CurrencyKey,
  FieldPreview,
  SpecialPanel,
  ThemeKey,
  TownBuildingDefinition,
} from './types';
import forgeIcon from './assets/icons/forge.svg';
import watchtowerIcon from './assets/icons/watchtower.svg';
import aetherPumpIcon from './assets/icons/aether-pump.svg';
import goldIcon from './assets/icons/gold.svg';
import scrapIcon from './assets/icons/scrap.svg';
import aetherIcon from './assets/icons/aether.svg';

export const themeOptions: Array<{ key: ThemeKey; label: string }> = [
  { key: 'seaMist', label: '블루 미스트' },
  { key: 'forestMoss', label: '포레스트' },
  { key: 'deepSlate', label: '슬레이트' },
  { key: 'sandDusk', label: '샌드' },
  { key: 'roseAsh', label: '로즈 애쉬' },
];

export const currencyIcons: Record<CurrencyKey, string> = {
  gold: goldIcon,
  scrap: scrapIcon,
  aether: aetherIcon,
};

export const currencyLabels: Record<CurrencyKey, string> = {
  gold: '식량',
  scrap: '목재',
  aether: '시간의 재화',
};

export const townBuildings: TownBuildingDefinition[] = [
  {
    id: 'house',
    name: '주인공의 집',
    description: '마을 성장의 기준이 되는 핵심 건물입니다. 다른 건물은 이 집보다 더 높게 올릴 수 없습니다.',
    category: 'house',
    icon: watchtowerIcon,
    maxLevel: 20,
    cost: { gold: 80n, scrap: 20n },
    baseDurationSeconds: 30,
    rewardText: '건물 최대 레벨 기준 상승',
  },
  {
    id: 'field',
    name: '밀밭',
    description: '식량을 안정적으로 생산하는 일반 건물입니다.',
    category: 'normal',
    icon: goldIcon,
    maxLevel: 20,
    cost: { gold: 35n, scrap: 10n },
    baseDurationSeconds: 24,
    rewardText: '매 분 식량 생산',
    production: { currency: 'gold', basePerMinute: 14n, perLevel: 8n },
  },
  {
    id: 'lumberyard',
    name: '벌목장',
    description: '목재를 확보하는 일반 건물입니다. 건축과 연구의 기본 재료를 안정적으로 공급합니다.',
    category: 'normal',
    icon: scrapIcon,
    maxLevel: 20,
    cost: { gold: 50n, scrap: 12n },
    baseDurationSeconds: 28,
    rewardText: '매 분 목재 생산',
    production: { currency: 'scrap', basePerMinute: 9n, perLevel: 6n },
  },
  {
    id: 'timeShrine',
    name: '시간 제단',
    description: '희귀한 시간의 재화를 조금씩 모읍니다. 초반 생산량은 낮지만 장기적으로 중요합니다.',
    category: 'normal',
    icon: aetherIcon,
    maxLevel: 15,
    cost: { gold: 120n, scrap: 60n },
    baseDurationSeconds: 42,
    rewardText: '매 분 시간의 재화 생산',
    production: { currency: 'aether', basePerMinute: 1n, perLevel: 1n },
  },
  {
    id: 'lab',
    name: '연구소',
    description: '플레이어 기본 스탯과 마을 관련 강화 연구를 진행합니다.',
    category: 'research',
    icon: aetherPumpIcon,
    maxLevel: 10,
    cost: { gold: 100n, scrap: 40n },
    baseDurationSeconds: 36,
    rewardText: '연구 탭 해금',
  },
  {
    id: 'forge',
    name: '대장간',
    description: '무기 추가, 장비 슬롯 확장 같은 장비 연구를 담당합니다.',
    category: 'forge',
    icon: forgeIcon,
    maxLevel: 10,
    cost: { gold: 110n, scrap: 55n },
    baseDurationSeconds: 38,
    rewardText: '대장간 탭 해금',
  },
  {
    id: 'builder',
    name: '건설소',
    description: '건축 시간 단축과 추가 건설 라인 연구를 담당합니다.',
    category: 'builder',
    icon: watchtowerIcon,
    maxLevel: 10,
    cost: { gold: 130n, scrap: 80n },
    baseDurationSeconds: 44,
    rewardText: '건설소 탭 해금',
  },
  {
    id: 'market',
    name: '시장',
    description: '장비 탈부착과 물류 관련 시스템이 열리는 특수 건물입니다.',
    category: 'market',
    icon: scrapIcon,
    maxLevel: 10,
    cost: { gold: 160n, scrap: 90n },
    baseDurationSeconds: 50,
    rewardText: '시장 탭 해금',
  },
  {
    id: 'inventory',
    name: '창고',
    description: '아이템 개수 확인과 보관을 담당합니다.',
    category: 'inventory',
    icon: goldIcon,
    maxLevel: 5,
    cost: { gold: 90n, scrap: 30n },
    baseDurationSeconds: 26,
    rewardText: '창고 탭 해금',
  },
  {
    id: 'fieldCollection',
    name: '기록관',
    description: '클리어한 필드와 제한 플레이 정보를 기록합니다.',
    category: 'fieldCollection',
    icon: watchtowerIcon,
    maxLevel: 5,
    cost: { gold: 140n, scrap: 45n },
    baseDurationSeconds: 40,
    rewardText: '필드 도감 탭 해금',
  },
  {
    id: 'enemyCollection',
    name: '박물관',
    description: '적 도감과 보스 기믹 기록을 보관합니다.',
    category: 'enemyCollection',
    icon: aetherPumpIcon,
    maxLevel: 5,
    cost: { gold: 150n, scrap: 55n },
    baseDurationSeconds: 40,
    rewardText: '적 도감 탭 해금',
  },
];

export const specialPanels: SpecialPanel[] = [
  {
    tabId: 'lab',
    name: '연구소',
    shortName: '연구소',
    description: '전투와 마을 양쪽에 적용되는 기본 연구입니다. 연구 완료 후 즉시 효과를 받습니다.',
    entries: [
      {
        id: 'lab-1',
        title: '농업 기록 정리',
        description: '마을 운영 효율을 높여 식량 생산의 기반을 다집니다.',
        effect: '식량 생산량 +8%',
        costText: '식량 120 / 목재 30',
      },
      {
        id: 'lab-2',
        title: '체력 단련',
        description: '전투 시작 시 적용되는 플레이어 기본 체력을 올립니다.',
        effect: '플레이어 기본 체력 +5',
        costText: '식량 90 / 목재 25',
      },
      {
        id: 'lab-3',
        title: '비축 규약',
        description: '마을의 보유 한도를 늘리는 운영 연구입니다.',
        effect: '식량 최대 보유량 +20%',
        costText: '식량 150 / 목재 40',
      },
    ],
  },
  {
    tabId: 'forge',
    name: '대장간',
    shortName: '대장간',
    description: '장비 카드와 장착 슬롯에 직접 연결되는 연구입니다.',
    entries: [
      {
        id: 'forge-1',
        title: '오른손 무기 틀',
        description: '외출 중 등장할 수 있는 기본 무기 종류를 해금합니다.',
        effect: '오른손 무기 카드 1종 추가',
        costText: '식량 140 / 목재 65',
      },
      {
        id: 'forge-2',
        title: '보조 슬롯 확장',
        description: '장비 장착 폭을 늘려 조합의 선택지를 넓힙니다.',
        effect: '보조 장비 슬롯 +1',
        costText: '식량 180 / 목재 90',
      },
      {
        id: 'forge-3',
        title: '도금 공정 개선',
        description: '장비 기본 효율을 높이는 정밀 공정 연구입니다.',
        effect: '장비 일반 스탯 계수 +6%',
        costText: '식량 220 / 목재 110',
      },
    ],
  },
  {
    tabId: 'builder',
    name: '건설소',
    shortName: '건설소',
    description: '건축 라인과 시간 단축을 다루는 특수 연구입니다.',
    entries: [
      {
        id: 'builder-1',
        title: '작업 순환 표준화',
        description: '건축에 드는 전체 시간을 줄입니다.',
        effect: '건축 시간 5% 단축',
        costText: '식량 120 / 목재 60',
      },
      {
        id: 'builder-2',
        title: '보조 인력 투입',
        description: '동시에 처리 가능한 마을 행동 수를 늘립니다.',
        effect: '행동 라인 +1',
        costText: '식량 260 / 목재 120 / 시간의 재화 2',
      },
      {
        id: 'builder-3',
        title: '현장 기록 보관',
        description: '완료된 건설 확인 흐름을 더 명확히 관리합니다.',
        effect: '건설 완료 확인 배지 표시',
        costText: '식량 90 / 목재 45',
      },
    ],
  },
  {
    tabId: 'market',
    name: '시장',
    shortName: '시장',
    description: '아이템과 장비의 이동, 탈부착 같은 물류 기능을 연구합니다.',
    entries: [
      {
        id: 'market-1',
        title: '장비 탈부착 허가',
        description: '상점과 전투 사이의 장비 교체 규칙 연구입니다.',
        effect: '장비 탈부착 기능 해금',
        costText: '식량 180 / 목재 80',
      },
      {
        id: 'market-2',
        title: '교환 기록 양식',
        description: '아이템 교환 시 필요한 정산 흐름을 준비합니다.',
        effect: '시장 기능 준비',
        costText: '식량 110 / 목재 70',
      },
    ],
  },
  {
    tabId: 'inventory',
    name: '창고',
    shortName: '창고',
    description: '아이템 개수 확인 중심의 보관 탭입니다.',
    entries: [
      {
        id: 'inventory-1',
        title: '시간의 재화',
        description: '건설과 연구를 가속화하는 소비형 아이템입니다.',
        effect: '건설/연구 남은 시간 감소',
        costText: '보유량 확인 전용',
      },
      {
        id: 'inventory-2',
        title: '재화 획득 꾸러미',
        description: '현재 생산 가능한 재화 중 하나를 랜덤으로 얻습니다.',
        effect: '최대 보유량을 넘겨 획득 가능',
        costText: '보유량 확인 전용',
      },
    ],
  },
  {
    tabId: 'fieldCollection',
    name: '기록관',
    shortName: '기록관',
    description: '필드 개방, 스테이지 진행, 제한 플레이 해금 기록을 모아보는 탭입니다.',
    entries: [
      {
        id: 'field-1',
        title: '초원 지대',
        description: '가장 먼저 개방되는 필드입니다.',
        effect: '제한 플레이 1종 준비 중',
        costText: '도감 기능 준비 중',
      },
      {
        id: 'field-2',
        title: '사막 지대',
        description: '다음 세계로 넘어가는 관문 필드입니다.',
        effect: '후속 필드 준비 중',
        costText: '도감 기능 준비 중',
      },
    ],
  },
  {
    tabId: 'enemyCollection',
    name: '박물관',
    shortName: '박물관',
    description: '적 도감과 보스 기믹 메모를 모아보는 탭입니다.',
    entries: [
      {
        id: 'enemy-1',
        title: '초원 도적',
        description: '초반 일반 적 역할의 기본형입니다.',
        effect: '일반 적 데이터 기록 예정',
        costText: '도감 기능 준비 중',
      },
      {
        id: 'enemy-2',
        title: '초원 감시자',
        description: '엘리트 적 예시입니다.',
        effect: '엘리트 적 데이터 기록 예정',
        costText: '도감 기능 준비 중',
      },
    ],
  },
];

export const fieldPreviews: FieldPreview[] = [
  {
    id: 'meadow',
    name: '초원',
    type: '초원',
    description: '가장 먼저 나가보는 기본 필드입니다. 일반/엘리트/보스 흐름만 가볍게 보여줍니다.',
    status: '준비중',
  },
  {
    id: 'desert',
    name: '사막',
    type: '사막',
    description: '후속 세계 필드입니다. 제한 플레이 구조가 붙을 예정입니다.',
    status: '준비중',
  },
];
